[directories]
astcachedir => /var/cache/asterisk
astetcdir => /etc/asterisk
astmoddir => /usr/lib/asterisk/modules
astvarlibdir => /var/lib/asterisk
astdbdir => /run/asterisk
astkeydir => /run/asterisk
astdatadir => /var/lib/asterisk
astagidir => /var/lib/asterisk/agi-bin
astspooldir => /var/spool/asterisk
astrundir => /run/asterisk
astlogdir => /var/log/asterisk
astsbindir => /usr/sbin

[options]
verbose = 4
debug = 1
nofork = yes
nocolor = yes
timestamp = yes
runuser = asterisk
rungroup = asterisk
defaultlanguage = en
documentation_language = en_US
live_dangerously = no
maxcalls = 10
maxfiles = 256
mindtmfduration = 40
